// <auto-generated />
namespace MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071459007_InitialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
